apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-inject
  namespace: akv-test
spec:
  vault:
    name: mwmakskeyvault # name of key vault
    object:
      name: inject-secret # name of the akv object
      type: secret # akv object type