apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-configmap-sync
  namespace: akv-test
spec:
  vault:
    name: mwmakskeyvault # name of key vault
    object:
      name: configmap-secret # name of the akv object
      type: secret # akv object type
  output:
    configMap:
      name: configmap-secret-from-akv # kubernetes configmap name
      dataKey: secret-value # key to store object value in kubernetes configmap
